name: fetteno-os
description: My Bluefin-DX development workstation for ThinkPad P14s

base-image: ghcr.io/ublue-os/bluefin-dx

modules:
  - type: rpm-ostree
    install:
      - fzf
      - bat

  - type: systemd
    system:
      enabled:
        - thinkpad-battery-manager.service

  - type: files
    files:
      - source: usr
        destination: /usr
      - source: etc
        destination: /etc
