name: Build ISO
on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Install BlueBuild CLI
        run: |
          curl -L https://github.com/blue-build/cli/releases/latest/download/bluebuild-x86_64-unknown-linux-gnu.tar.gz | tar -xzf -
          sudo mv bluebuild /usr/local/bin/

      - name: Generate ISO
        run: |
          sudo bluebuild generate-iso --iso-name fetteno-os.iso image ghcr.io/francesco-defalco/fetteno-os:latest

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: fetteno-os-iso
          path: ./*.iso
